#!/usr/bin/env python3
"""Tests for the ssh-reconcile script (~/.local/bin/ssh-reconcile).

Run with: python3 -m unittest discover ~/.config/yadm/tests
"""

import importlib.util
import json
import os
import stat
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path
from unittest.mock import MagicMock, patch

SCRIPT = os.path.expanduser("~/.local/bin/ssh-reconcile")

spec = importlib.util.spec_from_loader("ssh_reconcile", loader=None)
mod = importlib.util.module_from_spec(spec)
with open(SCRIPT, encoding="utf-8") as f:
    exec(compile(f.read(), SCRIPT, "exec"), mod.__dict__)


DUMMY_OPENSSH_KEY = """\
-----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAACmFlczI1Ni1jdHIAAAAGYmNyeXB0AAAAGAAAABCbpE8qmm
-----END OPENSSH PRIVATE KEY-----
"""

DUMMY_RSA_KEY = """\
-----BEGIN RSA PRIVATE KEY-----
MIIEowIBAAKCAQEA0Y3V7v...
-----END RSA PRIVATE KEY-----
"""

DUMMY_PUB_KEY = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIG... user@host\n"


class SshReconcileTests(unittest.TestCase):
    def setUp(self):
        self.tmp_dir = tempfile.TemporaryDirectory()
        self.ssh_path = Path(self.tmp_dir.name)

    def tearDown(self):
        self.tmp_dir.cleanup()

    def _create_file(self, name: str, content: str, mode: int = 0o600) -> Path:
        p = self.ssh_path / name
        p.write_text(content, encoding="utf-8")
        p.chmod(mode)
        return p

    def test_is_private_key_file(self):
        key1 = self._create_file("my_id_ed25519", DUMMY_OPENSSH_KEY)
        key2 = self._create_file("id_rsa", DUMMY_RSA_KEY)
        pub1 = self._create_file("my_id_ed25519.pub", DUMMY_PUB_KEY)
        config = self._create_file("config", "Host *\n  User test\n")
        known_hosts = self._create_file("known_hosts", "home.bean ssh-ed25519 ...\n")
        old_key = self._create_file("id_rsa.old", DUMMY_RSA_KEY)

        self.assertTrue(mod.is_private_key_file(key1))
        self.assertTrue(mod.is_private_key_file(key2))
        self.assertFalse(mod.is_private_key_file(pub1))
        self.assertFalse(mod.is_private_key_file(config))
        self.assertFalse(mod.is_private_key_file(known_hosts))
        self.assertFalse(mod.is_private_key_file(old_key))

    def test_discover_private_keys_ranking(self):
        self._create_file("id_rsa", DUMMY_RSA_KEY)
        self._create_file("MACHINE-ABC_id_ed25519", DUMMY_OPENSSH_KEY)
        self._create_file("other_key", DUMMY_OPENSSH_KEY)
        self._create_file("id_ed25519", DUMMY_OPENSSH_KEY)

        with patch.object(mod, "get_machine_identifiers", return_value=["MACHINE-ABC"]):
            discovered = mod.discover_private_keys(self.ssh_path)
            names = [k.name for k in discovered]
            # Machine specific key should be first
            self.assertEqual(names[0], "MACHINE-ABC_id_ed25519")
            # Standard keys next
            self.assertIn("id_ed25519", names[1:3])
            self.assertIn("id_rsa", names[1:3])
            # Other keys last
            self.assertEqual(names[-1], "other_key")

    def test_generate_config_local_content(self):
        key1 = self.ssh_path / "MACHINE-ABC_id_ed25519"
        key2 = self.ssh_path / "id_rsa"
        content = mod.generate_config_local_content([key1, key2], self.ssh_path)

        self.assertIn("IdentityFile ~/.ssh/MACHINE-ABC_id_ed25519", content)
        self.assertIn("IdentityFile ~/.ssh/id_rsa", content)
        self.assertIn("# Auto-generated by ssh-reconcile", content)

    def test_generate_config_local_content_empty(self):
        content = mod.generate_config_local_content([], self.ssh_path)
        self.assertIn("# No device-specific private keys discovered", content)

    def test_sync_config_local_creates_file_and_permissions(self):
        self._create_file("host1_id_ed25519", DUMMY_OPENSSH_KEY, mode=0o644)
        changed, keys, cfg_path = mod.sync_config_local(self.ssh_path)

        self.assertTrue(changed)
        self.assertEqual(len(keys), 1)
        self.assertTrue(cfg_path.is_file())

        # Check config_local content
        content = cfg_path.read_text(encoding="utf-8")
        self.assertIn("IdentityFile ~/.ssh/host1_id_ed25519", content)

        # Check permissions: 0600
        file_mode = stat.S_IMODE(cfg_path.stat().st_mode)
        self.assertEqual(file_mode, 0o600)

        # Re-running sync should detect no changes
        changed2, keys2, cfg_path2 = mod.sync_config_local(self.ssh_path)
        self.assertFalse(changed2)
        self.assertEqual(len(keys2), 1)

    def test_inspect_key_status(self):
        key = self._create_file("test_id_ed25519", DUMMY_OPENSSH_KEY)
        with patch("sys.platform", "darwin"):
            with patch.object(mod, "get_key_fingerprint", return_value="SHA256:dummyfingerprint"):
                with patch.object(mod, "is_key_in_apple_keychain", return_value=True):
                    st = mod.inspect_key_status(key, {"SHA256:dummyfingerprint"})
                    self.assertEqual(st["name"], "test_id_ed25519")
                    self.assertEqual(st["fingerprint"], "SHA256:dummyfingerprint")
                    self.assertTrue(st["in_agent"])
                    self.assertTrue(st["in_keychain"])

        with patch("sys.platform", "linux"):
            with patch.object(mod, "get_key_fingerprint", return_value="SHA256:dummyfingerprint"):
                st = mod.inspect_key_status(key, {"SHA256:dummyfingerprint"})
                self.assertIsNone(st["in_keychain"])

    def test_cli_subprocess_sync_and_status_json(self):
        self._create_file("test_box_id_ed25519", DUMMY_OPENSSH_KEY)

        # Run sync via CLI
        env = dict(os.environ, HOME=str(self.tmp_dir.name))
        ssh_target = Path(self.tmp_dir.name) / ".ssh"
        ssh_target.mkdir(parents=True, exist_ok=True)
        key_in_home = ssh_target / "test_box_id_ed25519"
        key_in_home.write_text(DUMMY_OPENSSH_KEY, encoding="utf-8")

        res_sync = subprocess.run(
            [sys.executable, SCRIPT, "sync"],
            env=env,
            capture_output=True,
            text=True,
            check=True,
        )
        self.assertIn("Updated", res_sync.stdout)

        # Run status --json via CLI
        res_status = subprocess.run(
            [sys.executable, SCRIPT, "status", "--json"],
            env=env,
            capture_output=True,
            text=True,
            check=True,
        )
        data = json.loads(res_status.stdout)
        self.assertIn("config_local", data)
        self.assertTrue(data["config_local"]["exists"])
        self.assertTrue(data["config_local"]["in_sync"])
        self.assertEqual(len(data["keys"]), 1)
        self.assertEqual(data["keys"][0]["name"], "test_box_id_ed25519")

    def test_cli_load_command(self):
        env = dict(os.environ, HOME=str(self.tmp_dir.name))
        ssh_target = Path(self.tmp_dir.name) / ".ssh"
        ssh_target.mkdir(parents=True, exist_ok=True)
        (ssh_target / "test_id_ed25519").write_text(DUMMY_OPENSSH_KEY, encoding="utf-8")

        res_load = subprocess.run(
            [sys.executable, SCRIPT, "load", "--quiet"],
            env=env,
            capture_output=True,
            text=True,
            check=True,
        )
        self.assertEqual(res_load.returncode, 0)
        config_local = ssh_target / "config_local"
        self.assertTrue(config_local.is_file())


if __name__ == "__main__":
    unittest.main()
