brew "certifi"
brew "colima", restart_service: :changed
brew "docker"
brew "docker-buildx"
brew "docker-compose"
brew "ffmpeg"
brew "gemini-cli"
brew "gh"
brew "mise"
brew "ralph-orchestrator"
brew "watch"
brew "xcodegen"
brew "yadm"
brew "yt-dlp"
brew "zoxide"
cask "claude-code"
cask "copilot-cli"
